server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.94.81.96/3307/yyl-demo
    username: root
    password: yin7372175240000
  session:
    store-type: none


  security:
    user:
      name: root
      password: 123
    basic:
      enabled: false
